# Generated by Django 4.2.3 on 2023-08-15 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('completedate', models.DateTimeField(blank=True, null=True)),
                ('category', models.IntegerField(choices=[(1, 'Junta Municipal de Agua y Saneamiento JMAS'), (2, 'Comision Federal de Electricidad CFE'), (3, 'Gas Natural'), (4, 'Direccion General de Desarrollo Urbano'), (5, 'Ecología y Protección Civil'), (6, 'Movilidad'), (7, 'Obras Públicas'), (8, 'Planeación del Desarrollo Municipal'), (9, 'Salud Pública'), (10, 'Otras')], default=1)),
                ('important', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
