# Generated by Django 4.2.3 on 2023-08-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_delete_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owmer',
            field=models.IntegerField(default=10),
        ),
    ]
